# Make sure to check the documentation at https://goreleaser.com
project_name: nav-site-server
before:
  hooks:
    - script\install-npm.bat
    # 请根据不同环境放开不同脚本windows为bat
#    - script\install-npm.sh
builds:
  - env:
      - CGO_ENABLED=0
#    binary: nav-site/nav-site-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.build={{.Version}}
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
#    meta: true
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    # nav-site-server_0.0.2-next_Linux_arm64.tar
#    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
